#!/bin/bash

DIR="`dirname \"$0\"`"

cd "$DIR/../core"
git remote rm origin
git remote add origin git@github.com:redberry-cas/core.git

cd ../physics
git remote rm origin
git remote add origin git@github.com:redberry-cas/physics.git

cd ../groovy
git remote rm origin
git remote add origin git@github.com:redberry-cas/groovy.git

cd ..
git submodule foreach git fetch
